CREATE TABLE IF NOT EXISTS account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(30)                      NOT NULL UNIQUE,
    email      VARCHAR(100)                     NOT NULL UNIQUE,
    password   VARCHAR(100)                     NOT NULL,
    is_enabled BOOLEAN   DEFAULT TRUE           NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS role
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS account_role
(
    account_id BIGINT NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    role_id    INT    NOT NULL REFERENCES role (id) ON DELETE CASCADE,
    PRIMARY KEY (account_id, role_id)
);

CREATE TABLE IF NOT EXISTS author
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS book
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255)         NOT NULL,
    pages          INT                  NOT NULL,
    price_in_cents INT                  NOT NULL,
    is_available   BOOLEAN DEFAULT TRUE NOT NULL,
    author_id      BIGINT               REFERENCES author (id) ON DELETE CASCADE
);